lexik_jwt_authentication:
    secret_key: '%kernel.project_dir%/config/jwt/private.pem' # chemin vers la clé privée
    public_key: '%kernel.project_dir%/config/jwt/public.pem'  # chemin vers la clé publique
    pass_phrase: '%env(JWT_PASSPHRASE)%'                      # phrase secrète utilisée pour générer les clés
    token_ttl: 3600                                           # durée de vie du token en secondes